default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  # database: quiz_development
  username: postgres
  password: password
  host: localhost

test:
  <<: *default
  # database: quiz_development
  username: postgres
  password: password
  host: localhost

production:
  <<: *default
  database: quiz_development
  url: <%= ENV['DATABASE_URL'] %>
